[[language]]
name = "html"
formatter = {command = "prettier" , args = ["--parser","html"]}

[[language]]
name = "json"
formatter = {command = 'prettier' , args = ["--parser","json"]}

[[language]]
name = "css"
formatter = {command = 'prettier' , args = ["--parser","css"]}


[[language]]
name = "javascript"
formatter = {command = 'prettier' , args = ["--parser","typescript"]}
auto-format = true


[[language]]
name = "typescript"
formatter = {command = 'prettier' , args = ["--parser","typescript"]}
auto-format = true


[[language]]
name = "tsx"
formatter = {command = 'prettier' , args = ["--parser","typescript"]}
auto-format = true

[[language]]
name = "typescript"
language-server = { command = "deno", args = ["lsp"] }

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
comment-token = "//"
formatter = {command = "rustfmt"}
indent = { tab-width = 4, unit = "    " }

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

