[[language]]
name = "html"
formatter = {command = 'C:\Users\syien\AppData\Roaming\npm\prettier.cmd' , args = ["--parser","html"]}

[[language]]
name = "json"
formatter = {command = 'C:\Users\syien\AppData\Roaming\npm\prettier.cmd' , args = ["--parser","json"]}

[[language]]
name = "css"
formatter = {command = 'C:\Users\syien\AppData\Roaming\npm\prettier.cmd' , args = ["--parser","css"]}


[[language]]
name = "javascript"
formatter = {command = 'C:\Users\syien\AppData\Roaming\npm\prettier.cmd' , args = ["--parser","typescript"]}
auto-format = true


[[language]]
name = "typescript"
formatter = {command = 'C:\Users\syien\AppData\Roaming\npm\prettier.cmd' , args = ["--parser","typescript"]}
auto-format = true


[[language]]
name = "tsx"
formatter = {command = 'C:\Users\syien\AppData\Roaming\npm\prettier.cmd' , args = ["--parser","typescript"]}
auto-format = true

